#Global Agent Configuration
#Tue Jun 02 09:25:18 EDT 2026
apiKey=sk-YOUR_SECURE_API_KEY_HERE
baseUrl=http\://localhost\:11434/
mcpAuth=Basic Z21fYWRtaW46Vk13YXJlMSE\=
mcpUrl=http\://10.85.69.214\:80/mcp
modelName=qwen3\:30b
provider=ollama
