#Global Agent Configuration
#Wed Jun 03 18:04:52 EDT 2026
apiKey=
baseUrl=http\://localhost\:11434/
mcpAuth=Basic Z21fYWRtaW46Vk13YXJlMSE\=
mcpUrl=http\://10.85.69.214\:80/mcp
modelName=qwen3\:30b
provider=ollama
