server:
  port: 8080

ollama:
  server:
    url: "http://localhost:11434"
  model:
    name: "qwen3:30b"
    timeout-seconds: 360

mcp:
  server: 
    url: http://<mcp server url or ip>/mcp
    auth-header: "Basic <gp mcp server auth header value>"

